#!/usr/bin/bash
set -e
set -x
set -u

IMAGESPATH="/var/lib/libvirt/images"
ISOPATH=/srv/ISOs
CLOUDINITPATH=/tmp/webcloudinits

## Fedora cloud image
# BASEIMAGE=Fedora-Cloud-Base-25-1.3.x86_64.qcow2
# BASEIMAGE_URL="https://download.fedoraproject.org/pub/fedora/linux/releases/25/CloudImages/x86_64/images/${BASEIMAGE}"

# Ubuntu
BASEIMAGE=ubuntu-16.04-server-cloudimg-amd64-disk1.img
BASEIMAGE_URL="https://cloud-images.ubuntu.com/releases/16.04/release/${BASEIMAGE}"
OS_VARIANT=ubuntu14.04
KERNEL_IMAGE=vmlinuz-4.4.0-59-generic
INITRD=initrd.img-4.4.0-59-generic

initDir(){
    mkdir -p ${ISOPATH}
    rm -Rvf ${CLOUDINITPATH}
    mkdir -p ${CLOUDINITPATH}
}

bootstrapSwarm(){
    export ANSIBLE_HOST_KEY_CHECKING=False
    ansible-playbook -i ./me-hosts ./cluster-setup.yml
}

downloadCloudImage(){
  wget -c - ${BASEIMAGE_URL} -O ./${BASEIMAGE} || echo return $?
  qemu-img convert -f raw -O qcow2 ${BASEIMAGE} ${BASEIMAGE}.qcow2
  ls -lah
}

extractKernel(){
    virt-builder --get-kernel ./${BASEIMAGE}
    cp -f  ${KERNEL_IMAGE} ${CLOUDINITPATH}/${KERNEL_IMAGE}
    cp -f  ${INITRD} ${CLOUDINITPATH}/${INITRD}

}

createVmImages(){
    rsync -a ./${BASEIMAGE}.qcow2 ${IMAGESPATH}/${1}.qcow2
}

setupCludConfig(){
    # Create webserver cloud-config
    rm -Rfv ${CLOUDINITPATH}/${1}
    mkdir -p ${CLOUDINITPATH}/${1}
    cp ./cloud-init/${1}/user-data ${CLOUDINITPATH}/${1}/user-data
    cp ./cloud-init/${1}/meta-data ${CLOUDINITPATH}/${1}/meta-data
}

startNginxContainer(){
    docker run \
       --name cloudinitserver \
       -d \
       -p 80:80 \
       -v ${CLOUDINITPATH}:/usr/share/nginx/html:ro nginx:1 \
   || docker restart cloudinitserver
}

createVM(){
    virsh --connect qemu:///system destroy ${1} || echo "${1} is not exist ... [ok]"
    virsh --connect qemu:///system undefine ${1} || echo "${1} is not exist ... [ok]"
    virt-install \
      --debug \
      --connect qemu:///system \
      --import \
      --name ${1} \
      --ram 1024 \
      --network bridge=virbr0 \
      --os-type=linux \
      --os-variant ${OS_VARIANT} \
      --disk path=${IMAGESPATH}/${1}.qcow2,format=qcow2,bus=virtio,device=disk \
      --boot hd,menu=on \
      --boot kernel=${CLOUDINITPATH}/${KERNEL_IMAGE},kernel_args="root=/dev/vda1 ro ds=nocloud-net;seedfrom=http://192.168.122.1:80/${1}/" &
      #--boot kernel=${CLOUDINITPATH}/${KERNEL_IMAGE},kernel_args="root=/dev/vda1 ro ds=nocloud-net;seedfrom=http://127.0.0.1:80/${1}/" &

      #  qemu-kvm -m 1024 \
      #      -drive file=${IMAGESPATH}/${1}.qcow2,format=qcow2,if=virtio,boot=on \
      #      -append "root=/dev/vda1 ro ds=nocloud-net;seedfrom=http://127.0.0.1:80/${1}" \
      #      -kernel ${CLOUDINITPATH}/${KERNEL_IMAGE} \
      #      -initrd ${CLOUDINITPATH}/${INITRD} &
#      -drive     -append 'root=/dev/vda1 ro ds=nocloud-net;s=http://127.0.0.1:80/${1}' &
}

getIPofVM(){
    virsh domifaddr ${item}
    virsh domiflist ${item}
}

abputVMs(){
    virsh list --all
    virsh -q list
    arp -e
    for item in $( virsh list --name); do
        echo "${item}"
        sudo virsh domiflist ${item}
    done
    cat /var/lib/libvirt/dnsmasq/*.status
}

bootstrapVM(){
    initDir
    downloadCloudImage
    extractKernel
    for item in $( ls ./cloud-init/); do
      	createVmImages ${item}
        setupCludConfig ${item}
    done
    startNginxContainer
    for item in $( ls ./cloud-init/); do
        createVM ${item}
    done
    sleep 5
    getIPofVM
    abputVMs
}

case "$1" in
        vm)
            bootstrapVM
            exit 0
            ;;

        swarm)
            bootstrapSwarm
            exit 0
            ;;

        help)
            echo $"Usage: $0 {vm|swarm|help}"
            exit 0
            ;;

        *)
            exit 0
            ;;

esac
